/* ==========================================
   HILLS TOUR & TRAVELS — HOME PAGE
   ========================================== */

import { createRoot } from 'react-dom/client';
import { createElement } from 'react';
import { destinations } from '../data/destinations.js';
import { packages } from '../data/packages.js';
import { HillsHero } from '../components/react/HillsHero.jsx';

export const Home = {
  render() {
    // Curate popular packages for homepage display
    const popularPackages = packages.filter(p => ["darjeeling-7-point", "gangtok-tsomgo-circuit", "gangtok-nathula-pass", "darjeeling-tiger-hill"].includes(p.id));

    return `
      <!-- 1. Cinematic Hero — React + framer-motion -->
      <div id="hills-hero-mount"></div>

      <!-- Build-your-route promo intentionally removed from home; route page still lives at /#/route -->


      <!-- 3. How It Works Section -->
      <section class="section-padding bg-surface-alt">
        <div class="container text-center">
          <span class="badge badge-brand"><i class="fa-solid fa-circle-info"></i> <span data-i18n="home.howBadge">Frictionless Mobility</span></span>
          <h2 class="section-title" data-i18n="home.howTitle">Book A Hill Ride In 30 Seconds</h2>
          <p class="section-subtitle" data-i18n="home.howSub">We have digitized mountain travel rules. No phone calling, no union bargaining.</p>

          <div class="grid grid-3" style="margin-top: 50px;">
            <div class="step-card glass-panel animate-scroll-reveal">
              <div class="step-badge">1</div>
              <i class="fa-solid fa-route step-icon"></i>
              <h3 data-i18n="home.step1">Choose Terminals</h3>
              <p>Type departures and drop-offs. Instant fuzzy autocomplete resolves spellings immediately.</p>
            </div>
            <div class="step-card glass-panel animate-scroll-reveal" style="animation-delay: 0.1s;">
              <div class="step-badge">2</div>
              <i class="fa-solid fa-car-rear step-icon"></i>
              <h3 data-i18n="home.step2">Select Mountain Fleet</h3>
              <p>Hatchbacks, luxury sedans, or rugged 4WD SUVs mandated for high altitude permit zones.</p>
            </div>
            <div class="step-card glass-panel animate-scroll-reveal" style="animation-delay: 0.2s;">
              <div class="step-badge">3</div>
              <i class="fa-solid fa-ticket step-icon"></i>
              <h3 data-i18n="home.step3">One-Click Checkout</h3>
              <p>Secure digital payment gateway. Permits are automatically generated by verified local partners.</p>
            </div>
          </div>
        </div>
      </section>

      <!-- 4. Curated Sightseeing Packages -->
      <section class="section-padding">
        <div class="container">
          <div class="text-center" style="margin-bottom: 50px;">
            <span class="badge badge-brand"><i class="fa-solid fa-sparkles"></i> Curated Expeditions</span>
            <h2 class="section-title" data-i18n="home.pkgTitle">Popular Sightseeing Modules</h2>
            <p class="section-subtitle">Fixed prices. All permits, driver lodging allowances, and border entries fully bundled.</p>
          </div>

          <div class="grid grid-2">
            ${popularPackages.map(pkg => {
              const dest = destinations.find(d => d.id === pkg.destinationId);
              return `
                <div class="package-card glass-panel ${pkg.isComingSoon ? '' : 'glass-panel-hover'} flex animate-scroll-reveal">
                  <div class="pkg-card-details">
                    <div class="flex-between" style="margin-bottom: 8px;">
                      <span class="pkg-dest-badge"><i class="fa-solid fa-location-dot"></i> ${dest.name}</span>
                      <div style="display: flex; gap: 8px; align-items: center;">
                        <span class="pkg-duration-badge" style="font-size: 0.75rem; padding: 4px 10px; background: rgba(255, 255, 255, 0.03); border: 1px solid var(--glass-border); border-radius: var(--radius-sm);"><i class="fa-solid fa-map-pin"></i> ${pkg.attractions.length}-Point</span>
                        <span class="pkg-duration-badge" style="font-size: 0.75rem; padding: 4px 10px; background: rgba(245, 158, 11, 0.08); border: 1px solid rgba(245, 158, 11, 0.2); border-radius: var(--radius-sm); color: var(--brand-color);"><i class="fa-solid fa-clock"></i> ${pkg.duration}</span>
                      </div>
                    </div>
                    <h3 class="pkg-title">${pkg.name}</h3>
                    <p class="pkg-desc">${pkg.description.slice(0, 100)}...</p>
                    
                    <div class="pkg-attractions">
                      <strong>Key Stops:</strong>
                      <ul>
                        ${pkg.attractions.slice(0, 3).map(att => `<li><i class="fa-solid fa-check"></i> ${att}</li>`).join("")}
                      </ul>
                    </div>

                    <div class="pkg-pricing-row flex-between">
                      ${pkg.isComingSoon ? `
                        <div class="pkg-price-col">
                          <span class="pkg-price-lbl">Pricing</span>
                          <div style="font-family: var(--font-mono); font-size: 1.1rem; font-weight: 700; color: var(--brand-color); display: flex; align-items: center; gap: 6px;"><i class="fa-solid fa-bell" style="font-size: 0.85rem;"></i> Enquire</div>
                        </div>
                        <a href="https://wa.me/919907219843?text=${encodeURIComponent('Hi! I\'m interested in the \"' + pkg.name + '\" package. Could you share pricing?')}" target="_blank" class="btn btn-primary" style="background: linear-gradient(135deg, #25d366, #128c7e);"><i class="fa-brands fa-whatsapp"></i> Enquire</a>
                      ` : `
                        <div class="pkg-price-col">
                          <span class="pkg-price-lbl">Starting From</span>
                          <div class="pkg-price-val">₹${pkg.priceSedan || pkg.priceSuv}</div>
                        </div>
                        <a href="#/booking?package=${pkg.id}" class="btn btn-primary">Book Package</a>
                      `}
                    </div>
                  </div>
                </div>
              `;
            }).join("")}
          </div>
          
          <div class="text-center" style="margin-top: 40px;">
            <a href="#/packages" class="btn btn-brand-outline"><span data-i18n="home.viewAll">View All Sightseeing Packages</span> <i class="fa-solid fa-arrow-right"></i></a>
          </div>
        </div>
      </section>


      <!-- 6. Trust Badges & Performance Metrics -->
      <section class="section-padding">
        <div class="container">
          <div class="grid grid-4 text-center">
            <div class="stat-card glass-panel animate-scroll-reveal">
              <i class="fa-solid fa-users stat-icon text-brand"></i>
              <div class="stat-number" data-target="3500">0</div>
              <p class="stat-label">Happy Tourists</p>
            </div>
            <div class="stat-card glass-panel animate-scroll-reveal" style="animation-delay: 0.1s;">
              <i class="fa-solid fa-route stat-icon text-brand"></i>
              <div class="stat-number" data-target="120">0</div>
              <p class="stat-label">Mapped Terminals</p>
            </div>
            <div class="stat-card glass-panel animate-scroll-reveal" style="animation-delay: 0.2s;">
              <i class="fa-solid fa-star-half-stroke stat-icon text-brand"></i>
              <div class="stat-number" data-target="4.9" data-decimals="1">0</div>
              <p class="stat-label">Google Rating (24 Reviews)</p>
            </div>
            <div class="stat-card glass-panel animate-scroll-reveal" style="animation-delay: 0.3s;">
              <i class="fa-solid fa-award stat-icon text-brand"></i>
              <div class="stat-number" data-target="100">0</div>
              <p class="stat-label">% Legal Permitting</p>
            </div>
          </div>
        </div>
      </section>

      <!-- 7. Customer Testimonials Slider -->
      <section class="section-padding bg-surface-alt">
        <div class="container text-center">
          <span class="badge badge-brand"><i class="fa-solid fa-comments"></i> Guest Journals</span>
          <h2 class="section-title" style="margin-bottom: 50px;" data-i18n="home.testiTitle">What Our Travelers Experience</h2>
          
          <div class="testimonial-slider glass-panel">
            <div class="testimonial-slide active">
              <i class="fa-solid fa-quote-left testimonial-quote-icon"></i>
              <p class="testimonial-text">"Booking a private SUV from Bagdogra to Gangtok was incredibly easy! The price was exactly as calculated online, and the permit handling for Tsomgo Lake was handled without any paperwork stress. Amazing service!"</p>
              <div class="testimonial-author">
                <strong>Ananya Sharma</strong>
                <span style="font-size: 0.8rem; color: var(--text-muted);">Travelled Oct 2025</span>
              </div>
            </div>
          </div>
        </div>
      </section>
    `;
  },

  init() {
    // 0. Mount the React + framer-motion hero
    const heroMount = document.getElementById('hills-hero-mount');
    if (heroMount) {
      try {
        this.heroRoot = createRoot(heroMount);
        this.heroRoot.render(createElement(HillsHero));
      } catch (err) {
        console.error('🚨 [Home] Failed to mount HillsHero:', err);
      }
    }

    // Booking widget moved to the dedicated /booking page — hero "Book Now" links there.


    // 4. Numbers Count-Up Animation
    const stats = document.querySelectorAll(".stat-number");
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          const el = entry.target;
          const target = parseFloat(el.getAttribute("data-target"));
          const decimals = parseInt(el.getAttribute("data-decimals") || "0");
          let current = 0;
          const increment = target / 30; // 30 steps
          
          const interval = setInterval(() => {
            current += increment;
            if (current >= target) {
              el.innerText = target.toFixed(decimals) + (target === 100 ? "%" : "+");
              clearInterval(interval);
            } else {
              el.innerText = current.toFixed(decimals) + (target === 100 ? "%" : "+");
            }
          }, 30);
          observer.unobserve(el);
        }
      });
    }, { threshold: 0.5 });

    stats.forEach(st => observer.observe(st));
  },

  destroy() {
    if (this.heroRoot) {
      try { this.heroRoot.unmount(); } catch (e) { /* noop */ }
      this.heroRoot = null;
    }
  }
};
